# Site settings
title: Oruj Karimov Portfolio
email: your-email@example.com
description: >- # this means ignore newlines until next property
  Portfolio of Oruj Karimov â€” engineering student passionate about web development and electronics.

# Base URL & URL
# For user/organization pages, leave baseurl empty
baseurl: "" # the subpath of your site, leave empty for username.github.io
url: "https://oruckerimova76-oss.github.io" # your site URL

# Author
author:
  name: Oruj Karimov
  email: your-email@example.com

# Build settings
markdown: kramdown
theme: minima # optional, if you want Jekyll theme support

# Optional
plugins:
  - jekyll-feed
